# Generated by Django 3.1.4 on 2021-07-02 07:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210702_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
