# Generated by Django 3.1.4 on 2020-12-10 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RD_Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subDomain',
        ),
    ]
