# Generated by Django 3.1.4 on 2020-12-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RD_Projects', '0002_remove_project_subdomain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubDomain',
        ),
    ]
