# Generated by Django 3.1.4 on 2021-06-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RD_Projects', '0005_auto_20210618_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
    ]
