# Generated by Django 3.1.4 on 2021-06-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RD_Projects', '0008_auto_20210621_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='voucherPDF',
            field=models.FileField(blank=True, null=True, upload_to='images/Project_voucherPDF'),
        ),
    ]
