# Generated by Django 3.1.4 on 2021-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RD_Projects', '0012_project_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
