# Generated by Django 3.1.4 on 2021-07-09 05:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('RD_Projects', '0014_service_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content1',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
