# Generated by Django 3.1.4 on 2021-08-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RD_Projects', '0016_remove_project_content1'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='images/Service_vouchers'),
        ),
        migrations.AddField(
            model_name='service',
            name='voucherPDF',
            field=models.FileField(blank=True, null=True, upload_to='images/Service_voucherPDF'),
        ),
    ]
