# Generated by Django 3.1.4 on 2021-07-02 06:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='images/blogs_img'),
        ),
    ]
