# Generated by Django 3.1.4 on 2021-07-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20210702_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='voucher',
            new_name='image',
        ),
    ]
